local ls = require("luasnip")
local s  = ls.snippet
local t  = ls.text_node
local i  = ls.insert_node

ls.add_snippets("tex", {
  s("template", {
    t("\\documentclass[11pt, a4paper]{article}"),
    t({"", ""}),
    t("\\usepackage[utf8]{inputenc}"),
    t({"", ""}),
    t("\\usepackage[T1]{fontenc}"),
    t({"", ""}),
    t("\\usepackage{amsmath, amssymb}"),
    t({"", ""}),
    t("\\usepackage{tikz-cd}"),
    t({"", ""}),
    t("\\usepackage{textcomp, gensymb}"),
    t({"", ""}),
    t("\\usepackage{parskip}"),
    t({"", ""}),
    t("\\usepackage{graphicx}"),
    t({"", ""}),
    t("\\usepackage{hyperref}"),
    t({"", ""}),
    t("\\usepackage{geometry}"),
    t({"", ""}),
    t("\\usetikzlibrary{positioning}"),
    t({"", ""}),
    t("\\newtheorem{theorem}{Theorem}"),
    t({"", ""}),
    t("\\newtheorem{lemma}[theorem]{Lemma}"),
    t({"", ""}),
    t("\\DeclareMathOperator{\\lcm}{lcm}"),
    t({"", ""}),
    t("\\DeclareMathOperator{\\ima}{im}"),
    t({"", ""}),
    t("\\geometry{margin=1in}"),
    t({"", ""}),
    t("\\hfuzz=50pt"),
    t({"", ""}),
    t({"", ""}),
    t("\\title{"), i(1, ""), t("}"),
    t({"", ""}),
    t("\\author{Nicholas Sales}"),
    t({"", ""}),
    t("\\date{\\today}"),
    t({"", ""}),
    t({"", ""}),
    t("\\begin{document}"),
    t({"", ""}),
    t({"", ""}),
    t("\\maketitle"),
    t({"", ""}),
    t("\\tableofcontents"),
    t({"", ""}),
    t("\\newpage"),
    t({"", ""}),
    t({"", ""}),
    t({"", ""}),
    t({"", ""}),
    t("\\end{document}"),
  }),
})

