#!/bin/bash
IFACE="$1"
STATUS="$2"
PIHOLE_DNS="dns here"
TARGET_SSID="home network"

if [ "$STATUS" = "up" ]; then
    SSID=$(iw dev "$IFACE" link | sed -n 's/^\s*SSID: //p')
    if [ "$SSID" = "$TARGET_SSID" ]; then
        resolvectl dns "$IFACE" "$PIHOLE_DNS"
        resolvectl domain "$IFACE" "~."
    else
        resolvectl revert "$IFACE"
    fi
fi

